### Project specific config ###
os: linux

jobs:
  include:
    - stage: test
      language: rust
      rust: stable
      env: ATOM_CHANNEL=stable
      script: skip
    - stage: test
      language: rust
      rust: beta
      env: ATOM_CHANNEL=beta
      script: skip
    - stage: test
      language: node_js
      node_js: lts/*
      install:
        - npm install
      script:
        - commitlint-travis
    - stage: release
      # Since the deploy needs APM, currently the simplest method is to run
      # build-package.sh, which requires the specs to pass, so this must run on Rust
      language: rust
      rust: stable
      script:
        - export PATH=${PATH}:${HOME}/atom/usr/bin/
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - nvm install lts/*
          - npx semantic-release

### Generic setup follows ###
install:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - "./build-package.sh"

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - "/^greenkeeper/.*$/"

git:
  depth: 10

dist: trusty
sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

stages:
  - test
  - name: release
    if: (NOT type = pull_request) AND branch = master
