### Project specific config ###
language: rust
rust: stable
os: linux

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

script:
  - commitlint-travis

jobs:
  include:
    - stage: release
      script:
        - export PATH=${PATH}:${HOME}/atom/usr/bin/
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - nvm install lts/*
          - npx semantic-release

### Generic setup follows ###
install:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - "./build-package.sh"

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - "/^greenkeeper/.*$/"

git:
  depth: 10

dist: trusty
sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

stages:
  - test
  - name: release
    if: (NOT type = pull_request) AND branch = master
