### Project specific config ###
os: linux

jobs:
  include:
    - stage: test
      language: rust
      rust: stable
      env: ATOM_CHANNEL=stable
      script: skip
    - stage: test
      language: rust
      rust: beta
      env: ATOM_CHANNEL=beta
      script: skip

### Generic setup follows ###
install: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - "/^greenkeeper/.*$/"

git:
  depth: 10

dist: trusty
sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
